version: "3"
services:
  app:
    image: app
    networks:
      - challenge-network
    container_name: challenge-frontend
    build:
      dockerfile: ./Dockerfile
      context: ./frontend/
    depends_on:
      - server
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules

  server:
    image: server
    networks:
      - challenge-network
    container_name: challenge-backend
    env_file:
      - ./backend/.env
    build:
      dockerfile: ./Dockerfile
      context: ./backend/
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/home/server
      - /home/server/node_modules
networks:
  challenge-network:
    driver: bridge
