version: "3"
services:
  app:
    image: app
    networks:
      - challenge-network
    container_name: challenge-frontend
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./
    depends_on:
      - server
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/home/app

  server:
    image: server
    networks:
      - challenge-network
    container_name: challenge-backend
    env_file:
      - ./backend/.env
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/home/server
networks:
  challenge-network:
    driver: bridge
